<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <UseWindowsForms>True</UseWindowsForms>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Management" Version="10.0.10" />
        <PackageReference Include="TaskScheduler" Version="2.12.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Logger\Logger.csproj" />
    </ItemGroup>

</Project>
