<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>$(TfmNet10WindowsSdk22000)</TargetFramework>
        <LangVersion>9</LangVersion>
        <UseWPF>true</UseWPF>
        <CsWinRTEnabled>false</CsWinRTEnabled>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <PropertyGroup>
        <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    </PropertyGroup>

    <Import Project="$(MSBuildThisFileDirectory).build\AutoVersion.props" />

    <ItemGroup>
        <Compile Remove="Properties\**" />
        <EmbeddedResource Remove="Properties\**" />
        <None Remove="Properties\**" />
        <Page Remove="Properties\**" />
        <None Update="settings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="plugin.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Ipc\IpcClient\IpcClient.csproj" />
        <ProjectReference Include="..\..\Plugin\Commons\Plugin.csproj" />
        <ProjectReference Include="..\ScreenCapture\ScreenCapture.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Helpers\" />
    </ItemGroup>

</Project>
