<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Logger\Logger.csproj" />
      <ProjectReference Include="..\Commons\Plugin.csproj" />
    </ItemGroup>

</Project>
