<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Helpers\Helpers.csproj" />
        <ProjectReference Include="..\..\Logger\Logger.csproj" />
        <ProjectReference Include="..\PluginContracts\PluginContracts.csproj" />
    </ItemGroup>

</Project>
