//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bridge.Resources.Langs.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Current Desktop:  的本地化字符串。
        /// </summary>
        internal static string Cluster_Notification_SVD_Current {
            get {
                return ResourceManager.GetString("Cluster.Notification.SVD.Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Desktop:  的本地化字符串。
        /// </summary>
        internal static string Cluster_Notification_SVD_Last {
            get {
                return ResourceManager.GetString("Cluster.Notification.SVD.Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 【{0}】 match rule 【{1}】, but error occur when moving.
        ///possible reason:
        ///- window invalid.
        ///- target desktop not exists.
        ///- target desktop invalid. 的本地化字符串。
        /// </summary>
        internal static string Error_MoveWindowToDesktop {
            get {
                return ResourceManager.GetString("Error.MoveWindowToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error! 的本地化字符串。
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot access task with your current permissions level.
        ///You need to run this application &apos;as administrator&apos; even if you are using an administrator account. 的本地化字符串。
        /// </summary>
        internal static string General_RunOnStartup_Error_Permission {
            get {
                return ResourceManager.GetString("General.RunOnStartup.Error.Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        internal static string hk_node_nav_down {
            get {
                return ResourceManager.GetString("hk_node_nav_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        internal static string hk_node_nav_left {
            get {
                return ResourceManager.GetString("hk_node_nav_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string hk_node_nav_right {
            get {
                return ResourceManager.GetString("hk_node_nav_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string hk_node_nav_up {
            get {
                return ResourceManager.GetString("hk_node_nav_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open AppController 的本地化字符串。
        /// </summary>
        internal static string hk_node_open_app_controller {
            get {
                return ResourceManager.GetString("hk_node_open_app_controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rise MainView 的本地化字符串。
        /// </summary>
        internal static string hk_node_rise_mainview {
            get {
                return ResourceManager.GetString("hk_node_rise_mainview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rise MainView For Active App 的本地化字符串。
        /// </summary>
        internal static string hk_node_rise_mainview_for_active_app {
            get {
                return ResourceManager.GetString("hk_node_rise_mainview_for_active_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rise MainView For Active App In Current Desktop 的本地化字符串。
        /// </summary>
        internal static string hk_node_rise_mainview_for_active_app_in_current_vd {
            get {
                return ResourceManager.GetString("hk_node_rise_mainview_for_active_app_in_current_vd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rise MainView For Current Desktop 的本地化字符串。
        /// </summary>
        internal static string hk_node_rise_mainview_for_current_vd {
            get {
                return ResourceManager.GetString("hk_node_rise_mainview_for_current_vd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Window Filter 的本地化字符串。
        /// </summary>
        internal static string hk_node_toggle_window_filter {
            get {
                return ResourceManager.GetString("hk_node_toggle_window_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop 的本地化字符串。
        /// </summary>
        internal static string K_D {
            get {
                return ResourceManager.GetString("K_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        internal static string K_D_N {
            get {
                return ResourceManager.GetString("K_D_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch 的本地化字符串。
        /// </summary>
        internal static string K_D_S {
            get {
                return ResourceManager.GetString("K_D_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string K_G {
            get {
                return ResourceManager.GetString("K_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        internal static string K_W {
            get {
                return ResourceManager.GetString("K_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        internal static string K_W_M {
            get {
                return ResourceManager.GetString("K_W_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move and Follow 的本地化字符串。
        /// </summary>
        internal static string K_W_MF {
            get {
                return ResourceManager.GetString("K_W_MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey Cleared. 的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_Cleared {
            get {
                return ResourceManager.GetString("KB.Hotkey.Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must choose a none-modifier Key. 的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_KeyCheck {
            get {
                return ResourceManager.GetString("KB.Hotkey.KeyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one modifier Key. 的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_MKeyCheck {
            get {
                return ResourceManager.GetString("KB.Hotkey.MKeyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move To Desktop  的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_MW {
            get {
                return ResourceManager.GetString("KB.Hotkey.MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move and Follow To Desktop  的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_MWF {
            get {
                return ResourceManager.GetString("KB.Hotkey.MWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register new Hotkey Failed. 的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_Reg_Fail {
            get {
                return ResourceManager.GetString("KB.Hotkey.Reg.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register new Hotkey Success. 的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_Reg_Success {
            get {
                return ResourceManager.GetString("KB.Hotkey.Reg.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings Saved. 的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_SettingsSaved {
            get {
                return ResourceManager.GetString("KB.Hotkey.SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch To Desktop  的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_SVD {
            get {
                return ResourceManager.GetString("KB.Hotkey.SVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Back To Last Desktop 的本地化字符串。
        /// </summary>
        internal static string KB_Hotkey_SVD_BACK_LAST {
            get {
                return ResourceManager.GetString("KB.Hotkey.SVD_BACK_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        internal static string Keys_Left {
            get {
                return ResourceManager.GetString("Keys.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Middle 的本地化字符串。
        /// </summary>
        internal static string Keys_Middle {
            get {
                return ResourceManager.GetString("Keys.Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string Keys_Right {
            get {
                return ResourceManager.GetString("Keys.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show ContextMenu 的本地化字符串。
        /// </summary>
        internal static string M_ContextMenu {
            get {
                return ResourceManager.GetString("M.ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop 的本地化字符串。
        /// </summary>
        internal static string M_D {
            get {
                return ResourceManager.GetString("M.D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Only Selected Desktop in View 的本地化字符串。
        /// </summary>
        internal static string M_D_DesktopShowForSelectedDesktop {
            get {
                return ResourceManager.GetString("M.D.DesktopShowForSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Desktop and Close View 的本地化字符串。
        /// </summary>
        internal static string M_D_DesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("M.D.DesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Desktop Only 的本地化字符串。
        /// </summary>
        internal static string M_D_DesktopVisibleOnly {
            get {
                return ResourceManager.GetString("M.D.DesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MainView 的本地化字符串。
        /// </summary>
        internal static string M_ROOT {
            get {
                return ResourceManager.GetString("M.ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        internal static string M_W {
            get {
                return ResourceManager.GetString("M.W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Window, Switch Desktop and Close View 的本地化字符串。
        /// </summary>
        internal static string M_W_WindowActiveDesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("M.W.WindowActiveDesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Window, Switch Desktop Only 的本地化字符串。
        /// </summary>
        internal static string M_W_WindowActiveDesktopVisibleOnly {
            get {
                return ResourceManager.GetString("M.W.WindowActiveDesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Window 的本地化字符串。
        /// </summary>
        internal static string M_W_WindowClose {
            get {
                return ResourceManager.GetString("M.W.WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide From View 的本地化字符串。
        /// </summary>
        internal static string M_W_WindowHideFromView {
            get {
                return ResourceManager.GetString("M.W.WindowHideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Windows Only From Selected App in Selected Desktop 的本地化字符串。
        /// </summary>
        internal static string M_W_WindowShowForSelectedProcessInSelectedDesktop {
            get {
                return ResourceManager.GetString("M.W.WindowShowForSelectedProcessInSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Windows Only From Selected App 的本地化字符串。
        /// </summary>
        internal static string M_W_WindowShowForSelectedProcessOnly {
            get {
                return ResourceManager.GetString("M.W.WindowShowForSelectedProcessOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Context Menu 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_ContextMenu {
            get {
                return ResourceManager.GetString("Mouse.Action.ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Only Selected Desktop in MainView 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_DesktopShowForSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopShowForSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Desktop And Close View 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Desktop Only 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do Nothing 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_DoNothing {
            get {
                return ResourceManager.GetString("Mouse.Action.DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Window, Switch Virtual Desktop And Close View 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Window, Switch Virtual Desktop Only 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Window 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowClose {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Windows Only From Selected App in Selected Desktop 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessInSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessInSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Windows Only From Selected App 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MouseAction Exists, try another combine or Mousebutton 的本地化字符串。
        /// </summary>
        internal static string Mouse_Tips_Exists {
            get {
                return ResourceManager.GetString("Mouse.Tips.Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string MsgBox_Caption_Confirm {
            get {
                return ResourceManager.GetString("MsgBox.Caption.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string MsgBox_Caption_Warning {
            get {
                return ResourceManager.GetString("MsgBox.Caption.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next row 的本地化字符串。
        /// </summary>
        internal static string Nav_CircleHType_NextRow {
            get {
                return ResourceManager.GetString("Nav.CircleHType.NextRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same row 的本地化字符串。
        /// </summary>
        internal static string Nav_CircleHType_SameRow {
            get {
                return ResourceManager.GetString("Nav.CircleHType.SameRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete this profile?
        ///All files related with this profile will be deleted too. 的本地化字符串。
        /// </summary>
        internal static string Profile_Confirm_Delete {
            get {
                return ResourceManager.GetString("Profile.Confirm.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid profile name, or profile name already exists. 的本地化字符串。
        /// </summary>
        internal static string Profile_Warning_InvalidProfileName {
            get {
                return ResourceManager.GetString("Profile.Warning.InvalidProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not rename or delete the last profile.
        ///Duplicate one and edit it. 的本地化字符串。
        /// </summary>
        internal static string Profile_Warning_LastProfileProtect {
            get {
                return ResourceManager.GetString("Profile.Warning.LastProfileProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one common rule is required. 的本地化字符串。
        /// </summary>
        internal static string Rule_AtLeastOne {
            get {
                return ResourceManager.GetString("Rule.AtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Regex. 的本地化字符串。
        /// </summary>
        internal static string Rule_InvalidRegex {
            get {
                return ResourceManager.GetString("Rule.InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is required. 的本地化字符串。
        /// </summary>
        internal static string Rule_NameRequired {
            get {
                return ResourceManager.GetString("Rule.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Rule 的本地化字符串。
        /// </summary>
        internal static string Rule_New {
            get {
                return ResourceManager.GetString("Rule.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is 的本地化字符串。
        /// </summary>
        internal static string Rule_Op_Eq {
            get {
                return ResourceManager.GetString("Rule.Op.Eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ends with 的本地化字符串。
        /// </summary>
        internal static string Rule_Op_Esw {
            get {
                return ResourceManager.GetString("Rule.Op.Esw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 regex 的本地化字符串。
        /// </summary>
        internal static string Rule_Op_Regex {
            get {
                return ResourceManager.GetString("Rule.Op.Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contains 的本地化字符串。
        /// </summary>
        internal static string Rule_Op_Sc {
            get {
                return ResourceManager.GetString("Rule.Op.Sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 starts with 的本地化字符串。
        /// </summary>
        internal static string Rule_Op_Ssw {
            get {
                return ResourceManager.GetString("Rule.Op.Ssw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string Tray_Menu_Quit {
            get {
                return ResourceManager.GetString("Tray.Menu.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Tray_Menu_Settings {
            get {
                return ResourceManager.GetString("Tray.Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Button Required 的本地化字符串。
        /// </summary>
        internal static string Validation_Mouse_Button_Required {
            get {
                return ResourceManager.GetString("Validation.Mouse.Button.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Virtual Desktop 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Desktop_Create {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Virtual Desktop 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Desktop_Remove {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhide Window 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Desktop_UnHideWindow {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.UnHideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Window_Close {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide from view 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Window_HideFromView {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.HideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Rule from this Window... 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Window_NewRule {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show windows from this app on all desktops 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Window_PinApp {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.PinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show this window on all desktops 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Window_PinWin {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.PinWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen 的本地化字符串。
        /// </summary>
        internal static string VDW_CTM_Window_Screen {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported Windows Version.
        ///Application Will Quit.
        ///
        ///Support List
        ///====================================
        ///Windows 10 Redstone5(17763)
        ///Windows 10 19H1(18362)
        ///Windows 10 19H2(18363)
        ///Windows 10 20H1(19041)
        ///Windows 10 20H2(19042)
        ///Windows 10 21H1(19043)
        ///Windows 10 21H2(19044)
        ///Windows 10 22H2(19045)
        ///Windows 11 21H2(22000)
        ///Windows 11 22H2(22621)
        ///Windows 11 23H2(22631)
        ///==================================== 的本地化字符串。
        /// </summary>
        internal static string VersionCheckFail {
            get {
                return ResourceManager.GetString("VersionCheckFail", resourceCulture);
            }
        }
    }
}
