//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualSpace.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings_zh_Hans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings_zh_Hans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bridge.Resources.Langs.WinFormStrings.zh-Hans", typeof(WinFormStrings_zh_Hans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前桌面：.
        /// </summary>
        internal static string Cluster_Notification_SVD_Current {
            get {
                return ResourceManager.GetString("Cluster.Notification.SVD.Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一个桌面：.
        /// </summary>
        internal static string Cluster_Notification_SVD_Last {
            get {
                return ResourceManager.GetString("Cluster.Notification.SVD.Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口 【{0}】 匹配规则 【{1}】，但移动时发生错误。
        ///可能的原因：
        ///- 窗口无效。
        ///- 目标桌面不存在。
        ///- 目标桌面无效。.
        /// </summary>
        internal static string Error_MoveWindowToDesktop {
            get {
                return ResourceManager.GetString("Error.MoveWindowToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误！.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前权限级别无法访问计划任务，
        ///请确保当前账户是此计算机的管理员并且“以管理员身份运行”运行此程序。.
        /// </summary>
        internal static string General_RunOnStartup_Error_Permission {
            get {
                return ResourceManager.GetString("General.RunOnStartup.Error.Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热键已清除。.
        /// </summary>
        internal static string KB_Hotkey_Cleared {
            get {
                return ResourceManager.GetString("KB.Hotkey.Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须选择一个非修改类键。.
        /// </summary>
        internal static string KB_Hotkey_KeyCheck {
            get {
                return ResourceManager.GetString("KB.Hotkey.KeyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动到桌面 .
        /// </summary>
        internal static string KB_Hotkey_MW {
            get {
                return ResourceManager.GetString("KB.Hotkey.MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动并跟随到桌面 .
        /// </summary>
        internal static string KB_Hotkey_MWF {
            get {
                return ResourceManager.GetString("KB.Hotkey.MWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热键注册失败。.
        /// </summary>
        internal static string KB_Hotkey_Reg_Fail {
            get {
                return ResourceManager.GetString("KB.Hotkey.Reg.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热键注册成功。.
        /// </summary>
        internal static string KB_Hotkey_Reg_Success {
            get {
                return ResourceManager.GetString("KB.Hotkey.Reg.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置已保存。.
        /// </summary>
        internal static string KB_Hotkey_SettingsSaved {
            get {
                return ResourceManager.GetString("KB.Hotkey.SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换到桌面 .
        /// </summary>
        internal static string KB_Hotkey_SVD {
            get {
                return ResourceManager.GetString("KB.Hotkey.SVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换回上一个桌面.
        /// </summary>
        internal static string KB_Hotkey_SVD_BACK_LAST {
            get {
                return ResourceManager.GetString("KB.Hotkey.SVD_BACK_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左键.
        /// </summary>
        internal static string Keys_Left {
            get {
                return ResourceManager.GetString("Keys.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中键.
        /// </summary>
        internal static string Keys_Middle {
            get {
                return ResourceManager.GetString("Keys.Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右键.
        /// </summary>
        internal static string Keys_Right {
            get {
                return ResourceManager.GetString("Keys.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示上下文菜单.
        /// </summary>
        internal static string Mouse_Action_ContextMenu {
            get {
                return ResourceManager.GetString("Mouse.Action.ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅显示所选桌面.
        /// </summary>
        internal static string Mouse_Action_DesktopShowForSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopShowForSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换虚拟桌面并关闭视图.
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅切换虚拟桌面.
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 什么都不做.
        /// </summary>
        internal static string Mouse_Action_DoNothing {
            get {
                return ResourceManager.GetString("Mouse.Action.DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 激活窗口，切换桌面并关闭视图.
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 激活窗口，切换桌面.
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭窗口.
        /// </summary>
        internal static string Mouse_Action_WindowClose {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅显示所选桌面中的活动程序窗口.
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessInSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessInSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅显示此程序的窗口.
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换到下一行.
        /// </summary>
        internal static string Nav_CircleHType_NextRow {
            get {
                return ResourceManager.GetString("Nav.CircleHType.NextRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在同一行内循环.
        /// </summary>
        internal static string Nav_CircleHType_SameRow {
            get {
                return ResourceManager.GetString("Nav.CircleHType.SameRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 至少需要一条窗口规则。.
        /// </summary>
        internal static string Rule_AtLeastOne {
            get {
                return ResourceManager.GetString("Rule.AtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的正则表达式。.
        /// </summary>
        internal static string Rule_InvalidRegex {
            get {
                return ResourceManager.GetString("Rule.InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是必须的。.
        /// </summary>
        internal static string Rule_NameRequired {
            get {
                return ResourceManager.GetString("Rule.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新规则.
        /// </summary>
        internal static string Rule_New {
            get {
                return ResourceManager.GetString("Rule.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        internal static string Rule_Op_Eq {
            get {
                return ResourceManager.GetString("Rule.Op.Eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以...结尾.
        /// </summary>
        internal static string Rule_Op_Esw {
            get {
                return ResourceManager.GetString("Rule.Op.Esw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正则表达式.
        /// </summary>
        internal static string Rule_Op_Regex {
            get {
                return ResourceManager.GetString("Rule.Op.Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包含.
        /// </summary>
        internal static string Rule_Op_Sc {
            get {
                return ResourceManager.GetString("Rule.Op.Sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以...开头.
        /// </summary>
        internal static string Rule_Op_Ssw {
            get {
                return ResourceManager.GetString("Rule.Op.Ssw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建新的虚拟桌面.
        /// </summary>
        internal static string VDW_CTM_Desktop_Create {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除虚拟桌面.
        /// </summary>
        internal static string VDW_CTM_Desktop_Remove {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消隐藏窗口.
        /// </summary>
        internal static string VDW_CTM_Desktop_UnHideWindow {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.UnHideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string VDW_CTM_Window_Close {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从视图中隐藏.
        /// </summary>
        internal static string VDW_CTM_Window_HideFromView {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.HideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为此窗口创建规则....
        /// </summary>
        internal static string VDW_CTM_Window_NewRule {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在所有桌面上显示此应用的窗口.
        /// </summary>
        internal static string VDW_CTM_Window_PinApp {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.PinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在所有桌面上显示此窗口.
        /// </summary>
        internal static string VDW_CTM_Window_PinWin {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.PinWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 屏幕.
        /// </summary>
        internal static string VDW_CTM_Window_Screen {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的 Windows 版本
        ///应用程序将退出
        ///
        ///支持的列表
        ///====================================
        ///VirtualSpace10	Windows 10	Redstone5(17763)
        ///VirtualSpace10	Windows 10	19H1(18362)
        ///VirtualSpace10	Windows 10	19H2(18363)
        ///VirtualSpace10	Windows 10	20H1(19041)
        ///VirtualSpace10	Windows 10	20H2(19042)
        ///VirtualSpace10	Windows 10	21H1(19043)
        ///VirtualSpace10	Windows 10	21H2(19044)
        ///VirtualSpace10	Windows 10	22H2(19045)
        ///VirtualSpace(11)	Windows 11	21H2(22000)
        ///VirtualSpace(11)	Windows 11	22H2(22621)
        ///====================================.
        /// </summary>
        internal static string VersionCheckFail {
            get {
                return ResourceManager.GetString("VersionCheckFail", resourceCulture);
            }
        }
    }
}
