//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.Resources.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bridge.Resources.Langs.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Desktop: .
        /// </summary>
        internal static string Cluster_Notification_SVD_Current {
            get {
                return ResourceManager.GetString("Cluster.Notification.SVD.Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Desktop: .
        /// </summary>
        internal static string Cluster_Notification_SVD_Last {
            get {
                return ResourceManager.GetString("Cluster.Notification.SVD.Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window 【{0}】 match rule 【{1}】, but error occur when moving.
        ///possible reason:
        ///- window invalid.
        ///- target desktop not exists.
        ///- target desktop invalid..
        /// </summary>
        internal static string Error_MoveWindowToDesktop {
            get {
                return ResourceManager.GetString("Error.MoveWindowToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access task with your current permissions level.
        ///You need to run this application &apos;as administrator&apos; even if you are using an administrator account..
        /// </summary>
        internal static string General_RunOnStartup_Error_Permission {
            get {
                return ResourceManager.GetString("General.RunOnStartup.Error.Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string hk_node_nav_down {
            get {
                return ResourceManager.GetString("hk_node_nav_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string hk_node_nav_left {
            get {
                return ResourceManager.GetString("hk_node_nav_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string hk_node_nav_right {
            get {
                return ResourceManager.GetString("hk_node_nav_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string hk_node_nav_up {
            get {
                return ResourceManager.GetString("hk_node_nav_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open AppController.
        /// </summary>
        internal static string hk_node_open_app_controller {
            get {
                return ResourceManager.GetString("hk_node_open_app_controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise MainView.
        /// </summary>
        internal static string hk_node_rise_mainview {
            get {
                return ResourceManager.GetString("hk_node_rise_mainview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise MainView For Active App.
        /// </summary>
        internal static string hk_node_rise_mainview_for_active_app {
            get {
                return ResourceManager.GetString("hk_node_rise_mainview_for_active_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise MainView For Active App In Current Desktop.
        /// </summary>
        internal static string hk_node_rise_mainview_for_active_app_in_current_vd {
            get {
                return ResourceManager.GetString("hk_node_rise_mainview_for_active_app_in_current_vd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise MainView For Current Desktop.
        /// </summary>
        internal static string hk_node_rise_mainview_for_current_vd {
            get {
                return ResourceManager.GetString("hk_node_rise_mainview_for_current_vd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Window Filter.
        /// </summary>
        internal static string hk_node_toggle_window_filter {
            get {
                return ResourceManager.GetString("hk_node_toggle_window_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string K_D {
            get {
                return ResourceManager.GetString("K_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string K_D_N {
            get {
                return ResourceManager.GetString("K_D_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string K_D_S {
            get {
                return ResourceManager.GetString("K_D_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string K_G {
            get {
                return ResourceManager.GetString("K_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string K_W {
            get {
                return ResourceManager.GetString("K_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string K_W_M {
            get {
                return ResourceManager.GetString("K_W_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move and Follow.
        /// </summary>
        internal static string K_W_MF {
            get {
                return ResourceManager.GetString("K_W_MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey Cleared..
        /// </summary>
        internal static string KB_Hotkey_Cleared {
            get {
                return ResourceManager.GetString("KB.Hotkey.Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must choose a none-modifier Key..
        /// </summary>
        internal static string KB_Hotkey_KeyCheck {
            get {
                return ResourceManager.GetString("KB.Hotkey.KeyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one modifier Key..
        /// </summary>
        internal static string KB_Hotkey_MKeyCheck {
            get {
                return ResourceManager.GetString("KB.Hotkey.MKeyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Desktop .
        /// </summary>
        internal static string KB_Hotkey_MW {
            get {
                return ResourceManager.GetString("KB.Hotkey.MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move and Follow To Desktop .
        /// </summary>
        internal static string KB_Hotkey_MWF {
            get {
                return ResourceManager.GetString("KB.Hotkey.MWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new Hotkey Failed..
        /// </summary>
        internal static string KB_Hotkey_Reg_Fail {
            get {
                return ResourceManager.GetString("KB.Hotkey.Reg.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new Hotkey Success..
        /// </summary>
        internal static string KB_Hotkey_Reg_Success {
            get {
                return ResourceManager.GetString("KB.Hotkey.Reg.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved..
        /// </summary>
        internal static string KB_Hotkey_SettingsSaved {
            get {
                return ResourceManager.GetString("KB.Hotkey.SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch To Desktop .
        /// </summary>
        internal static string KB_Hotkey_SVD {
            get {
                return ResourceManager.GetString("KB.Hotkey.SVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Back To Last Desktop.
        /// </summary>
        internal static string KB_Hotkey_SVD_BACK_LAST {
            get {
                return ResourceManager.GetString("KB.Hotkey.SVD_BACK_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Keys_Left {
            get {
                return ResourceManager.GetString("Keys.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string Keys_Middle {
            get {
                return ResourceManager.GetString("Keys.Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Keys_Right {
            get {
                return ResourceManager.GetString("Keys.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ContextMenu.
        /// </summary>
        internal static string M_ContextMenu {
            get {
                return ResourceManager.GetString("M.ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string M_D {
            get {
                return ResourceManager.GetString("M.D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Selected Desktop in View.
        /// </summary>
        internal static string M_D_DesktopShowForSelectedDesktop {
            get {
                return ResourceManager.GetString("M.D.DesktopShowForSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Desktop and Close View.
        /// </summary>
        internal static string M_D_DesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("M.D.DesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Desktop Only.
        /// </summary>
        internal static string M_D_DesktopVisibleOnly {
            get {
                return ResourceManager.GetString("M.D.DesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainView.
        /// </summary>
        internal static string M_ROOT {
            get {
                return ResourceManager.GetString("M.ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string M_W {
            get {
                return ResourceManager.GetString("M.W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Window, Switch Desktop and Close View.
        /// </summary>
        internal static string M_W_WindowActiveDesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("M.W.WindowActiveDesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Window, Switch Desktop Only.
        /// </summary>
        internal static string M_W_WindowActiveDesktopVisibleOnly {
            get {
                return ResourceManager.GetString("M.W.WindowActiveDesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        internal static string M_W_WindowClose {
            get {
                return ResourceManager.GetString("M.W.WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide From View.
        /// </summary>
        internal static string M_W_WindowHideFromView {
            get {
                return ResourceManager.GetString("M.W.WindowHideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows Only From Selected App in Selected Desktop.
        /// </summary>
        internal static string M_W_WindowShowForSelectedProcessInSelectedDesktop {
            get {
                return ResourceManager.GetString("M.W.WindowShowForSelectedProcessInSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows Only From Selected App.
        /// </summary>
        internal static string M_W_WindowShowForSelectedProcessOnly {
            get {
                return ResourceManager.GetString("M.W.WindowShowForSelectedProcessOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Context Menu.
        /// </summary>
        internal static string Mouse_Action_ContextMenu {
            get {
                return ResourceManager.GetString("Mouse.Action.ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Selected Desktop in MainView.
        /// </summary>
        internal static string Mouse_Action_DesktopShowForSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopShowForSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Desktop And Close View.
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Desktop Only.
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing.
        /// </summary>
        internal static string Mouse_Action_DoNothing {
            get {
                return ResourceManager.GetString("Mouse.Action.DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Window, Switch Virtual Desktop And Close View.
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Window, Switch Virtual Desktop Only.
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        internal static string Mouse_Action_WindowClose {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows Only From Selected App in Selected Desktop.
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessInSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessInSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows Only From Selected App.
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MouseAction Exists, try another combine or Mousebutton.
        /// </summary>
        internal static string Mouse_Tips_Exists {
            get {
                return ResourceManager.GetString("Mouse.Tips.Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string MsgBox_Caption_Confirm {
            get {
                return ResourceManager.GetString("MsgBox.Caption.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MsgBox_Caption_Warning {
            get {
                return ResourceManager.GetString("MsgBox.Caption.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next row.
        /// </summary>
        internal static string Nav_CircleHType_NextRow {
            get {
                return ResourceManager.GetString("Nav.CircleHType.NextRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same row.
        /// </summary>
        internal static string Nav_CircleHType_SameRow {
            get {
                return ResourceManager.GetString("Nav.CircleHType.SameRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this profile?
        ///All files related with this profile will be deleted too..
        /// </summary>
        internal static string Profile_Confirm_Delete {
            get {
                return ResourceManager.GetString("Profile.Confirm.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid profile name, or profile name already exists..
        /// </summary>
        internal static string Profile_Warning_InvalidProfileName {
            get {
                return ResourceManager.GetString("Profile.Warning.InvalidProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not rename or delete the last profile.
        ///Duplicate one and edit it..
        /// </summary>
        internal static string Profile_Warning_LastProfileProtect {
            get {
                return ResourceManager.GetString("Profile.Warning.LastProfileProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one common rule is required..
        /// </summary>
        internal static string Rule_AtLeastOne {
            get {
                return ResourceManager.GetString("Rule.AtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Regex..
        /// </summary>
        internal static string Rule_InvalidRegex {
            get {
                return ResourceManager.GetString("Rule.InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required..
        /// </summary>
        internal static string Rule_NameRequired {
            get {
                return ResourceManager.GetString("Rule.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule.
        /// </summary>
        internal static string Rule_New {
            get {
                return ResourceManager.GetString("Rule.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        internal static string Rule_Op_Eq {
            get {
                return ResourceManager.GetString("Rule.Op.Eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        internal static string Rule_Op_Esw {
            get {
                return ResourceManager.GetString("Rule.Op.Esw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regex.
        /// </summary>
        internal static string Rule_Op_Regex {
            get {
                return ResourceManager.GetString("Rule.Op.Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string Rule_Op_Sc {
            get {
                return ResourceManager.GetString("Rule.Op.Sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        internal static string Rule_Op_Ssw {
            get {
                return ResourceManager.GetString("Rule.Op.Ssw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Tray_Menu_Quit {
            get {
                return ResourceManager.GetString("Tray.Menu.Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Tray_Menu_Settings {
            get {
                return ResourceManager.GetString("Tray.Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Button Required.
        /// </summary>
        internal static string Validation_Mouse_Button_Required {
            get {
                return ResourceManager.GetString("Validation.Mouse.Button.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Virtual Desktop.
        /// </summary>
        internal static string VDW_CTM_Desktop_Create {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Virtual Desktop.
        /// </summary>
        internal static string VDW_CTM_Desktop_Remove {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide Window.
        /// </summary>
        internal static string VDW_CTM_Desktop_UnHideWindow {
            get {
                return ResourceManager.GetString("VDW.CTM.Desktop.UnHideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string VDW_CTM_Window_Close {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide from view.
        /// </summary>
        internal static string VDW_CTM_Window_HideFromView {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.HideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Rule from this Window....
        /// </summary>
        internal static string VDW_CTM_Window_NewRule {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show windows from this app on all desktops.
        /// </summary>
        internal static string VDW_CTM_Window_PinApp {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.PinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this window on all desktops.
        /// </summary>
        internal static string VDW_CTM_Window_PinWin {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.PinWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        internal static string VDW_CTM_Window_Screen {
            get {
                return ResourceManager.GetString("VDW.CTM.Window.Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Windows Version.
        ///Application Will Quit.
        ///
        ///Support List
        ///====================================
        ///Windows 10 Redstone5(17763)
        ///Windows 10 19H1(18362)
        ///Windows 10 19H2(18363)
        ///Windows 10 20H1(19041)
        ///Windows 10 20H2(19042)
        ///Windows 10 21H1(19043)
        ///Windows 10 21H2(19044)
        ///Windows 10 22H2(19045)
        ///Windows 11 21H2(22000)
        ///Windows 11 22H2(22621)
        ///Windows 11 23H2(22631)
        ///====================================.
        /// </summary>
        internal static string VersionCheckFail {
            get {
                return ResourceManager.GetString("VersionCheckFail", resourceCulture);
            }
        }
    }
}
