<Project>
    <ItemGroup>
        <VirtualDesktopEmbed Include="$(MSBuildProjectDirectory)\..\VirtualDesktop\VirtualDesktop10\VirtualDesktop10.csproj" />
        <VirtualDesktopEmbed Include="$(MSBuildProjectDirectory)\..\VirtualDesktop\VirtualDesktop11\VirtualDesktop11.csproj" />
        <VirtualDesktopEmbed Include="$(MSBuildProjectDirectory)\..\VirtualDesktop\VirtualDesktop11_21H2\VirtualDesktop11_21H2.csproj" />
        <VirtualDesktopEmbed Include="$(MSBuildProjectDirectory)\..\VirtualDesktop\VirtualDesktop11_23H2\VirtualDesktop11_23H2.csproj" />
        <VirtualDesktopEmbed Include="$(MSBuildProjectDirectory)\..\VirtualDesktop\VirtualDesktop11_23H2_3085\VirtualDesktop11_23H2_3085.csproj" />
        <VirtualDesktopEmbed Include="$(MSBuildProjectDirectory)\..\VirtualDesktop\VirtualDesktop11_24H2\VirtualDesktop11_24H2.csproj" />
    </ItemGroup>
</Project>
