<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0-windows</TargetFrameworks>
        <Nullable>enable</Nullable>
        <CsWinRTEnabled>false</CsWinRTEnabled>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0-windows' Or '$(TargetFramework)' == 'net6.0-windows' ">
        <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Bridge\Bridge.csproj" />
    </ItemGroup>

</Project>
