//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPanel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlPanel.Resources.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Dialogs_Cancel {
            get {
                return ResourceManager.GetString("Dialogs.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Dialogs_OK {
            get {
                return ResourceManager.GetString("Dialogs.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Generic_Filter {
            get {
                return ResourceManager.GetString("Generic.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Generic_Name {
            get {
                return ResourceManager.GetString("Generic.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string logTab_Menu_Clear {
            get {
                return ResourceManager.GetString("logTab.Menu.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string logTabDebug {
            get {
                return ResourceManager.GetString("logTabDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string logTabError {
            get {
                return ResourceManager.GetString("logTabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string logTabEvent {
            get {
                return ResourceManager.GetString("logTabEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string logTabInfo {
            get {
                return ResourceManager.GetString("logTabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        internal static string logTabVerbose {
            get {
                return ResourceManager.GetString("logTabVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string logTabWarning {
            get {
                return ResourceManager.GetString("logTabWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this window.
        /// </summary>
        internal static string Menus_Commons_Close {
            get {
                return ResourceManager.GetString("Menus.Commons.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Menus_Commons_Restart {
            get {
                return ResourceManager.GetString("Menus.Commons.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run As Administrator.
        /// </summary>
        internal static string Menus_Commons_RunAsAdmin {
            get {
                return ResourceManager.GetString("Menus.Commons.RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Application.
        /// </summary>
        internal static string Menus_Commons_Shutdown {
            get {
                return ResourceManager.GetString("Menus.Commons.Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Theme.
        /// </summary>
        internal static string Menus_Commons_Theme_Change {
            get {
                return ResourceManager.GetString("Menus.Commons.Theme.Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all logs.
        /// </summary>
        internal static string Menus_Logs_ClearAll {
            get {
                return ResourceManager.GetString("Menus.Logs.ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder....
        /// </summary>
        internal static string Menus_Logs_OpenLogsDir {
            get {
                return ResourceManager.GetString("Menus.Logs.OpenLogsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Context Menu.
        /// </summary>
        internal static string Mouse_Action_ContextMenu {
            get {
                return ResourceManager.GetString("Mouse.Action.ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Selected Desktop in MainView.
        /// </summary>
        internal static string Mouse_Action_DesktopShowForSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopShowForSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Desktop And Close View.
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Desktop Only.
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing.
        /// </summary>
        internal static string Mouse_Action_DoNothing {
            get {
                return ResourceManager.GetString("Mouse.Action.DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Window, Switch Virtual Desktop And Close View.
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Window, Switch Virtual Desktop Only.
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        internal static string Mouse_Action_WindowClose {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide From View.
        /// </summary>
        internal static string Mouse_Action_WindowHideFromView {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowHideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows Only From Selected App in Selected Desktop.
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessInSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessInSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Windows Only From Selected App.
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string NavBar_About {
            get {
                return ResourceManager.GetString("NavBar.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string NavBar_Control {
            get {
                return ResourceManager.GetString("NavBar.Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string NavBar_General {
            get {
                return ResourceManager.GetString("NavBar.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string NavBar_Help {
            get {
                return ResourceManager.GetString("NavBar.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string NavBar_Logs {
            get {
                return ResourceManager.GetString("NavBar.Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string NavBar_Plugins {
            get {
                return ResourceManager.GetString("NavBar.Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string NavBar_Rules {
            get {
                return ResourceManager.GetString("NavBar.Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string NavBar_Settings {
            get {
                return ResourceManager.GetString("NavBar.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string NavBar_Theme {
            get {
                return ResourceManager.GetString("NavBar.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        internal static string NavBar_UI {
            get {
                return ResourceManager.GetString("NavBar.UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: If and only when the number of virtual desktops is the square of the natural number [1,n], the arrangement can be changed; 
        ///if the conditions are not satisfied, the program will automatically reset to the first arrangement..
        /// </summary>
        internal static string Note_DesktopArrangement {
            get {
                return ResourceManager.GetString("Note.DesktopArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: more details such as delay of start can be set in.
        /// </summary>
        internal static string Note_General_Label_TaskScheduler {
            get {
                return ResourceManager.GetString("Note.General.Label.TaskScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: KeyBindings, MouseActions, LogConfigs and StorageConfigs are shared by all profiles(regardless of profiles). 
        ///some settings may need restart program to take effect..
        /// </summary>
        internal static string Note_Settings_Profiles {
            get {
                return ResourceManager.GetString("Note.Settings.Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: change config folder need restart program. this operation only change location, no files will be copied or moved to avoid overwrite files unexpectedly. 
        ///if you want reuse current configs, you may manually copy &quot;Related Content&quot; to the folder you choosed, then restart program.
        ///Related Content: Settings.json, Profiles\*.*.
        /// </summary>
        internal static string Note_Settings_Storage {
            get {
                return ResourceManager.GetString("Note.Settings.Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear and Save.
        /// </summary>
        internal static string Page_Control_KB_ClearSave {
            get {
                return ResourceManager.GetString("Page.Control.KB.ClearSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate.
        /// </summary>
        internal static string Page_Control_KB_Extra {
            get {
                return ResourceManager.GetString("Page.Control.KB.Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register and Save.
        /// </summary>
        internal static string Page_Control_KB_RegSave {
            get {
                return ResourceManager.GetString("Page.Control.KB.RegSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string Page_Control_Keyboard {
            get {
                return ResourceManager.GetString("Page.Control.Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        internal static string Page_Control_Mouse {
            get {
                return ResourceManager.GetString("Page.Control.Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When mouse hover on Taskbar, Use wheel switch virtual desktop..
        /// </summary>
        internal static string Page_Control_Mouse_UseWheelSwitchDesktopWhenOnTaskbar {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.UseWheelSwitchDesktopWhenOnTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT+Scroll Up =&gt; Go Up.
        /// </summary>
        internal static string Page_Control_Mouse_Wheel_Down {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.Wheel.Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT+Scroll Down =&gt; Go Down.
        /// </summary>
        internal static string Page_Control_Mouse_Wheel_SDown {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.Wheel.SDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Down =&gt; Go Right.
        /// </summary>
        internal static string Page_Control_Mouse_Wheel_SUp {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.Wheel.SUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Up =&gt; Go Left.
        /// </summary>
        internal static string Page_Control_Mouse_Wheel_Up {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.Wheel.Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🖇️.
        /// </summary>
        internal static string Page_Control_MouseAction_Behavior {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind.
        /// </summary>
        internal static string Page_Control_MouseAction_Bind {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Page_Control_MouseAction_Clear {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select the MouseAction from the left side of the 🖇️ icon, then choose a behavior from the right side of the 🖇️ icon, and finally bind..
        /// </summary>
        internal static string Page_Control_MouseAction_DesktopBindings {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.DesktopBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand for details..
        /// </summary>
        internal static string Page_Control_MouseAction_ExpanderHeader {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.ExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a virtual desktop in the MainView.
        /// </summary>
        internal static string Page_Control_MouseAction_OnDesktop {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.OnDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a window thumbnail in the MainView.
        /// </summary>
        internal static string Page_Control_MouseAction_OnThumb {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.OnThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Page_Control_MouseAction_Save {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select the MouseAction from the left side of the 🖇️ icon, then choose a behavior from the right side of the 🖇️ icon, and finally bind..
        /// </summary>
        internal static string Page_Control_MouseAction_WindowBindings {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.WindowBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Page_Control_MouseButtons_Left {
            get {
                return ResourceManager.GetString("Page.Control.MouseButtons.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string Page_Control_MouseButtons_Middle {
            get {
                return ResourceManager.GetString("Page.Control.MouseButtons.Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Page_Control_MouseButtons_Right {
            get {
                return ResourceManager.GetString("Page.Control.MouseButtons.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string Page_General_Basics {
            get {
                return ResourceManager.GetString("Page.General.Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        internal static string Page_General_Cluster {
            get {
                return ResourceManager.GetString("Page.General.Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the MainView shown, [Double LShift] to open WindowFilter..
        /// </summary>
        internal static string Page_General_EnableWindowFilter {
            get {
                return ResourceManager.GetString("Page.General.EnableWindowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When use hotkey rise the MainView, Close it if the MainView already shown..
        /// </summary>
        internal static string Page_General_HideMainViewIfItsShown {
            get {
                return ResourceManager.GetString("Page.General.HideMainViewIfItsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide MainView when program start..
        /// </summary>
        internal static string Page_General_HideOnStart {
            get {
                return ResourceManager.GetString("Page.General.HideOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable circulation..
        /// </summary>
        internal static string Page_General_Nav_H {
            get {
                return ResourceManager.GetString("Page.General.Nav.H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right end of row joins to left end of:.
        /// </summary>
        internal static string Page_General_Nav_HType {
            get {
                return ResourceManager.GetString("Page.General.Nav.HType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next row.
        /// </summary>
        internal static string Page_General_Nav_HType_0 {
            get {
                return ResourceManager.GetString("Page.General.Nav.HType.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same row.
        /// </summary>
        internal static string Page_General_Nav_HType_1 {
            get {
                return ResourceManager.GetString("Page.General.Nav.HType.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulate vertically. (same col only).
        /// </summary>
        internal static string Page_General_Nav_V {
            get {
                return ResourceManager.GetString("Page.General.Nav.V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Page_General_Navigation {
            get {
                return ResourceManager.GetString("Page.General.Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification when Current virtual desktop changed..
        /// </summary>
        internal static string Page_General_NotificationOnVdChanged {
            get {
                return ResourceManager.GetString("Page.General.NotificationOnVdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch program at system startup..
        /// </summary>
        internal static string Page_General_RunOnStartup {
            get {
                return ResourceManager.GetString("Page.General.RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show virtual desktop index on Tray Icon..
        /// </summary>
        internal static string Page_General_ShowVDIndexOnTrayIcon {
            get {
                return ResourceManager.GetString("Page.General.ShowVDIndexOnTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Page_General_StyleOfVDIndexOnTrayIcon_0 {
            get {
                return ResourceManager.GetString("Page.General.StyleOfVDIndexOnTrayIcon.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast 1.
        /// </summary>
        internal static string Page_General_StyleOfVDIndexOnTrayIcon_1 {
            get {
                return ResourceManager.GetString("Page.General.StyleOfVDIndexOnTrayIcon.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast 2.
        /// </summary>
        internal static string Page_General_StyleOfVDIndexOnTrayIcon_2 {
            get {
                return ResourceManager.GetString("Page.General.StyleOfVDIndexOnTrayIcon.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler.
        /// </summary>
        internal static string Page_General_TaskScheduler {
            get {
                return ResourceManager.GetString("Page.General.TaskScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Logs In GUI.
        /// </summary>
        internal static string Page_Logs_IsPrintLogs {
            get {
                return ResourceManager.GetString("Page.Logs.IsPrintLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Page_Plugins_Author {
            get {
                return ResourceManager.GetString("Page.Plugins.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Page_Plugins_Close {
            get {
                return ResourceManager.GetString("Page.Plugins.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emai.
        /// </summary>
        internal static string Page_Plugins_Email {
            get {
                return ResourceManager.GetString("Page.Plugins.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Page_Plugins_Name {
            get {
                return ResourceManager.GetString("Page.Plugins.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string Page_Plugins_Operations {
            get {
                return ResourceManager.GetString("Page.Plugins.Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Page_Plugins_Restart {
            get {
                return ResourceManager.GetString("Page.Plugins.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Page_Plugins_Settings {
            get {
                return ResourceManager.GetString("Page.Plugins.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Page_Plugins_Version {
            get {
                return ResourceManager.GetString("Page.Plugins.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string Page_Rules_Add {
            get {
                return ResourceManager.GetString("Page.Rules.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string Page_Rules_Clone {
            get {
                return ResourceManager.GetString("Page.Rules.Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Page_Rules_Created {
            get {
                return ResourceManager.GetString("Page.Rules.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove(Del).
        /// </summary>
        internal static string Page_Rules_Delete {
            get {
                return ResourceManager.GetString("Page.Rules.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit(E)....
        /// </summary>
        internal static string Page_Rules_Edit {
            get {
                return ResourceManager.GetString("Page.Rules.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Rule Definition.
        /// </summary>
        internal static string Page_Rules_EditRule {
            get {
                return ResourceManager.GetString("Page.Rules.EditRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule Definition.
        /// </summary>
        internal static string Page_Rules_NewRule {
            get {
                return ResourceManager.GetString("Page.Rules.NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string Page_Rules_Rule_Basic {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Page_Rules_Rule_CloseDefBox {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.CloseDefBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line.
        /// </summary>
        internal static string Page_Rules_Rule_CommandLine {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.CommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Page_Rules_Rule_Created {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Page_Rules_Rule_Enabled {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Window.
        /// </summary>
        internal static string Page_Rules_Rule_FollowWindow {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.FollowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide From View.
        /// </summary>
        internal static string Page_Rules_Rule_HideFromView {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.HideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Desktop.
        /// </summary>
        internal static string Page_Rules_Rule_MoveToDesktop {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.MoveToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Screen.
        /// </summary>
        internal static string Page_Rules_Rule_MoveToScreen {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.MoveToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        internal static string Page_Rules_Rule_Op_esw {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Op.esw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regex.
        /// </summary>
        internal static string Page_Rules_Rule_Op_rim {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Op.rim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string Page_Rules_Rule_Op_sc {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Op.sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        internal static string Page_Rules_Rule_Op_ssw {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Op.ssw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Window.
        /// </summary>
        internal static string Page_Rules_Rule_PinApp {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.PinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Application of Window.
        /// </summary>
        internal static string Page_Rules_Rule_PinWindow {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        internal static string Page_Rules_Rule_ProcessName {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Path.
        /// </summary>
        internal static string Page_Rules_Rule_ProcessPath {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.ProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        internal static string Page_Rules_Rule_Save {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag(Group).
        /// </summary>
        internal static string Page_Rules_Rule_Tag {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        internal static string Page_Rules_Rule_Title {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Page_Rules_Rule_Updated {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Actions.
        /// </summary>
        internal static string Page_Rules_Rule_WindowActions {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.WindowActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Window Rules.
        /// </summary>
        internal static string Page_Rules_Rule_WindowRules {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.WindowRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window In Screen.
        /// </summary>
        internal static string Page_Rules_Rule_WinInScreen {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.WinInScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Class.
        /// </summary>
        internal static string Page_Rules_Rule_WndClass {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.WndClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag(Group).
        /// </summary>
        internal static string Page_Rules_Tag {
            get {
                return ResourceManager.GetString("Page.Rules.Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Page_Rules_Updated {
            get {
                return ResourceManager.GetString("Page.Rules.Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Page_Rules_Weight {
            get {
                return ResourceManager.GetString("Page.Rules.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Page_Settings_Language {
            get {
                return ResourceManager.GetString("Page.Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Page_Settings_Menus_Delete {
            get {
                return ResourceManager.GetString("Page.Settings.Menus.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Page_Settings_Menus_Duplicate {
            get {
                return ResourceManager.GetString("Page.Settings.Menus.Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Page_Settings_Menus_Rename {
            get {
                return ResourceManager.GetString("Page.Settings.Menus.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Page_Settings_ProfileManager {
            get {
                return ResourceManager.GetString("Page.Settings.ProfileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string Page_Settings_Storage {
            get {
                return ResourceManager.GetString("Page.Settings.Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        internal static string Page_Settings_Storage_ChangeConfigPath {
            get {
                return ResourceManager.GetString("Page.Settings.Storage.ChangeConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Folder of Configs.
        /// </summary>
        internal static string Page_Settings_Storage_ConfigRootPath {
            get {
                return ResourceManager.GetString("Page.Settings.Storage.ConfigRootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Page_Settings_Theme {
            get {
                return ResourceManager.GetString("Page.Settings.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Page_Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Page.Settings.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Page_Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Page.Settings.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string Page_Settings_Theme_Sys {
            get {
                return ResourceManager.GetString("Page.Settings.Theme.Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopLeft to BottomRight, Horizontal.
        /// </summary>
        internal static string Page_UI_Label_m0 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopRight to BottomLeft, Horizontal.
        /// </summary>
        internal static string Page_UI_Label_m1 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BottomLeft to TopRight, Horizontal.
        /// </summary>
        internal static string Page_UI_Label_m2 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BottomRight to TopLeft, Horizontal.
        /// </summary>
        internal static string Page_UI_Label_m3 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopLeft to BottomRight, Vertical.
        /// </summary>
        internal static string Page_UI_Label_m4 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopRight to BottomLeft, Vertical.
        /// </summary>
        internal static string Page_UI_Label_m5 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BottomLeft to TopRight, Vertical.
        /// </summary>
        internal static string Page_UI_Label_m6 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BottomRight to TopLeft, Vertical.
        /// </summary>
        internal static string Page_UI_Label_m7 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Virtual Desktop Index.
        /// </summary>
        internal static string Page_UI_ShowVdIndex {
            get {
                return ResourceManager.GetString("Page.UI.ShowVdIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-based.
        /// </summary>
        internal static string Page_UI_ShowVdIndex_OneBased {
            get {
                return ResourceManager.GetString("Page.UI.ShowVdIndex.OneBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-based.
        /// </summary>
        internal static string Page_UI_ShowVdIndex_ZeroBased {
            get {
                return ResourceManager.GetString("Page.UI.ShowVdIndex.ZeroBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Virtual Desktop Name.
        /// </summary>
        internal static string Page_UI_ShowVdName {
            get {
                return ResourceManager.GetString("Page.UI.ShowVdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Desktop Arrangement.
        /// </summary>
        internal static string Page_UI_VdArrangement {
            get {
                return ResourceManager.GetString("Page.UI.VdArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Desktop View.
        /// </summary>
        internal static string Page_UI_VdView {
            get {
                return ResourceManager.GetString("Page.UI.VdView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required..
        /// </summary>
        internal static string Validation_Error_Required {
            get {
                return ResourceManager.GetString("Validation.Error.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Definition.
        /// </summary>
        internal static string Window_RuleDefinition {
            get {
                return ResourceManager.GetString("Window.RuleDefinition", resourceCulture);
            }
        }
    }
}
