//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPanel.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlPanel.Resources.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Dialogs_Cancel {
            get {
                return ResourceManager.GetString("Dialogs.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Dialogs_OK {
            get {
                return ResourceManager.GetString("Dialogs.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string Generic_Filter {
            get {
                return ResourceManager.GetString("Generic.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Generic_Name {
            get {
                return ResourceManager.GetString("Generic.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string logTab_Menu_Clear {
            get {
                return ResourceManager.GetString("logTab.Menu.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string logTabDebug {
            get {
                return ResourceManager.GetString("logTabDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string logTabError {
            get {
                return ResourceManager.GetString("logTabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string logTabEvent {
            get {
                return ResourceManager.GetString("logTabEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string logTabInfo {
            get {
                return ResourceManager.GetString("logTabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verbose 的本地化字符串。
        /// </summary>
        internal static string logTabVerbose {
            get {
                return ResourceManager.GetString("logTabVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string logTabWarning {
            get {
                return ResourceManager.GetString("logTabWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close this window 的本地化字符串。
        /// </summary>
        internal static string Menus_Commons_Close {
            get {
                return ResourceManager.GetString("Menus.Commons.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        internal static string Menus_Commons_Restart {
            get {
                return ResourceManager.GetString("Menus.Commons.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run As Administrator 的本地化字符串。
        /// </summary>
        internal static string Menus_Commons_RunAsAdmin {
            get {
                return ResourceManager.GetString("Menus.Commons.RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown Application 的本地化字符串。
        /// </summary>
        internal static string Menus_Commons_Shutdown {
            get {
                return ResourceManager.GetString("Menus.Commons.Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Theme 的本地化字符串。
        /// </summary>
        internal static string Menus_Commons_Theme_Change {
            get {
                return ResourceManager.GetString("Menus.Commons.Theme.Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear all logs 的本地化字符串。
        /// </summary>
        internal static string Menus_Logs_ClearAll {
            get {
                return ResourceManager.GetString("Menus.Logs.ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Logs Folder... 的本地化字符串。
        /// </summary>
        internal static string Menus_Logs_OpenLogsDir {
            get {
                return ResourceManager.GetString("Menus.Logs.OpenLogsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Context Menu 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_ContextMenu {
            get {
                return ResourceManager.GetString("Mouse.Action.ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Only Selected Desktop in MainView 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_DesktopShowForSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopShowForSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Desktop And Close View 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Desktop Only 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_DesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.DesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do Nothing 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_DoNothing {
            get {
                return ResourceManager.GetString("Mouse.Action.DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Window, Switch Virtual Desktop And Close View 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleAndCloseView {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleAndCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Window, Switch Virtual Desktop Only 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowActiveDesktopVisibleOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowActiveDesktopVisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Window 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowClose {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide From View 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowHideFromView {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowHideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Windows Only From Selected App in Selected Desktop 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessInSelectedDesktop {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessInSelectedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Windows Only From Selected App 的本地化字符串。
        /// </summary>
        internal static string Mouse_Action_WindowShowForSelectedProcessOnly {
            get {
                return ResourceManager.GetString("Mouse.Action.WindowShowForSelectedProcessOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control 的本地化字符串。
        /// </summary>
        internal static string NavBar_Control {
            get {
                return ResourceManager.GetString("NavBar.Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string NavBar_General {
            get {
                return ResourceManager.GetString("NavBar.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string NavBar_Help {
            get {
                return ResourceManager.GetString("NavBar.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logs 的本地化字符串。
        /// </summary>
        internal static string NavBar_Logs {
            get {
                return ResourceManager.GetString("NavBar.Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        internal static string NavBar_Plugins {
            get {
                return ResourceManager.GetString("NavBar.Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules 的本地化字符串。
        /// </summary>
        internal static string NavBar_Rules {
            get {
                return ResourceManager.GetString("NavBar.Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string NavBar_Settings {
            get {
                return ResourceManager.GetString("NavBar.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string NavBar_Theme {
            get {
                return ResourceManager.GetString("NavBar.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI 的本地化字符串。
        /// </summary>
        internal static string NavBar_UI {
            get {
                return ResourceManager.GetString("NavBar.UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: If and only when the number of virtual desktops is the square of the natural number [1,n], the arrangement can be changed; 
        ///if the conditions are not satisfied, the program will automatically reset to the first arrangement. 的本地化字符串。
        /// </summary>
        internal static string Note_DesktopArrangement {
            get {
                return ResourceManager.GetString("Note.DesktopArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: more details such as delay of start can be set in 的本地化字符串。
        /// </summary>
        internal static string Note_General_Label_TaskScheduler {
            get {
                return ResourceManager.GetString("Note.General.Label.TaskScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: KeyBindings, MouseActions, LogConfigs and StorageConfigs are shared by all profiles(regardless of profiles). 
        ///some settings may need restart program to take effect. 的本地化字符串。
        /// </summary>
        internal static string Note_Settings_Profiles {
            get {
                return ResourceManager.GetString("Note.Settings.Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: change config folder need restart program. this operation only change location, no files will be copied or moved to avoid overwrite files unexpectedly. 
        ///if you want reuse current configs, you may manually copy &quot;Related Content&quot; to the folder you choosed, then restart program.
        ///Related Content: Settings.json, Profiles\*.* 的本地化字符串。
        /// </summary>
        internal static string Note_Settings_Storage {
            get {
                return ResourceManager.GetString("Note.Settings.Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear and Save 的本地化字符串。
        /// </summary>
        internal static string Page_Control_KB_ClearSave {
            get {
                return ResourceManager.GetString("Page.Control.KB.ClearSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternate 的本地化字符串。
        /// </summary>
        internal static string Page_Control_KB_Extra {
            get {
                return ResourceManager.GetString("Page.Control.KB.Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register and Save 的本地化字符串。
        /// </summary>
        internal static string Page_Control_KB_RegSave {
            get {
                return ResourceManager.GetString("Page.Control.KB.RegSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard 的本地化字符串。
        /// </summary>
        internal static string Page_Control_Keyboard {
            get {
                return ResourceManager.GetString("Page.Control.Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse 的本地化字符串。
        /// </summary>
        internal static string Page_Control_Mouse {
            get {
                return ResourceManager.GetString("Page.Control.Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When mouse hover on Taskbar, Use wheel switch virtual desktop. 的本地化字符串。
        /// </summary>
        internal static string Page_Control_Mouse_UseWheelSwitchDesktopWhenOnTaskbar {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.UseWheelSwitchDesktopWhenOnTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHIFT+Scroll Up =&gt; Go Up 的本地化字符串。
        /// </summary>
        internal static string Page_Control_Mouse_Wheel_Down {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.Wheel.Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHIFT+Scroll Down =&gt; Go Down 的本地化字符串。
        /// </summary>
        internal static string Page_Control_Mouse_Wheel_SDown {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.Wheel.SDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll Down =&gt; Go Right 的本地化字符串。
        /// </summary>
        internal static string Page_Control_Mouse_Wheel_SUp {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.Wheel.SUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll Up =&gt; Go Left 的本地化字符串。
        /// </summary>
        internal static string Page_Control_Mouse_Wheel_Up {
            get {
                return ResourceManager.GetString("Page.Control.Mouse.Wheel.Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🖇️ 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_Behavior {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bind 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_Bind {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_Clear {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First select the MouseAction from the left side of the 🖇️ icon, then choose a behavior from the right side of the 🖇️ icon, and finally bind. 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_DesktopBindings {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.DesktopBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand for details. 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_ExpanderHeader {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.ExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on a virtual desktop in the MainView 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_OnDesktop {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.OnDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on a window thumbnail in the MainView 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_OnThumb {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.OnThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_Save {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First select the MouseAction from the left side of the 🖇️ icon, then choose a behavior from the right side of the 🖇️ icon, and finally bind. 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseAction_WindowBindings {
            get {
                return ResourceManager.GetString("Page.Control.MouseAction.WindowBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseButtons_Left {
            get {
                return ResourceManager.GetString("Page.Control.MouseButtons.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Middle 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseButtons_Middle {
            get {
                return ResourceManager.GetString("Page.Control.MouseButtons.Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string Page_Control_MouseButtons_Right {
            get {
                return ResourceManager.GetString("Page.Control.MouseButtons.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basics 的本地化字符串。
        /// </summary>
        internal static string Page_General_Basics {
            get {
                return ResourceManager.GetString("Page.General.Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cluster 的本地化字符串。
        /// </summary>
        internal static string Page_General_Cluster {
            get {
                return ResourceManager.GetString("Page.General.Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When use hotkey rise the MainView, Close it if the MainView already shown. 的本地化字符串。
        /// </summary>
        internal static string Page_General_HideMainViewIfItsShown {
            get {
                return ResourceManager.GetString("Page.General.HideMainViewIfItsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide MainView when program start. 的本地化字符串。
        /// </summary>
        internal static string Page_General_HideOnStart {
            get {
                return ResourceManager.GetString("Page.General.HideOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable circulation. 的本地化字符串。
        /// </summary>
        internal static string Page_General_Nav_H {
            get {
                return ResourceManager.GetString("Page.General.Nav.H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right end of row joins to left end of: 的本地化字符串。
        /// </summary>
        internal static string Page_General_Nav_HType {
            get {
                return ResourceManager.GetString("Page.General.Nav.HType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next row 的本地化字符串。
        /// </summary>
        internal static string Page_General_Nav_HType_0 {
            get {
                return ResourceManager.GetString("Page.General.Nav.HType.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same row 的本地化字符串。
        /// </summary>
        internal static string Page_General_Nav_HType_1 {
            get {
                return ResourceManager.GetString("Page.General.Nav.HType.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circulate vertically. (same col only) 的本地化字符串。
        /// </summary>
        internal static string Page_General_Nav_V {
            get {
                return ResourceManager.GetString("Page.General.Nav.V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        internal static string Page_General_Navigation {
            get {
                return ResourceManager.GetString("Page.General.Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show notification when Current virtual desktop changed. 的本地化字符串。
        /// </summary>
        internal static string Page_General_NotificationOnVdChanged {
            get {
                return ResourceManager.GetString("Page.General.NotificationOnVdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch program at system startup. 的本地化字符串。
        /// </summary>
        internal static string Page_General_RunOnStartup {
            get {
                return ResourceManager.GetString("Page.General.RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show virtual desktop index on Tray Icon. 的本地化字符串。
        /// </summary>
        internal static string Page_General_ShowVDIndexOnTrayIcon {
            get {
                return ResourceManager.GetString("Page.General.ShowVDIndexOnTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Page_General_StyleOfVDIndexOnTrayIcon_0 {
            get {
                return ResourceManager.GetString("Page.General.StyleOfVDIndexOnTrayIcon.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Contrast 1 的本地化字符串。
        /// </summary>
        internal static string Page_General_StyleOfVDIndexOnTrayIcon_1 {
            get {
                return ResourceManager.GetString("Page.General.StyleOfVDIndexOnTrayIcon.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Contrast 2 的本地化字符串。
        /// </summary>
        internal static string Page_General_StyleOfVDIndexOnTrayIcon_2 {
            get {
                return ResourceManager.GetString("Page.General.StyleOfVDIndexOnTrayIcon.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Scheduler 的本地化字符串。
        /// </summary>
        internal static string Page_General_TaskScheduler {
            get {
                return ResourceManager.GetString("Page.General.TaskScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Logs In GUI 的本地化字符串。
        /// </summary>
        internal static string Page_Logs_IsPrintLogs {
            get {
                return ResourceManager.GetString("Page.Logs.IsPrintLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        internal static string Page_Plugins_Author {
            get {
                return ResourceManager.GetString("Page.Plugins.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Page_Plugins_Close {
            get {
                return ResourceManager.GetString("Page.Plugins.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emai 的本地化字符串。
        /// </summary>
        internal static string Page_Plugins_Email {
            get {
                return ResourceManager.GetString("Page.Plugins.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Page_Plugins_Name {
            get {
                return ResourceManager.GetString("Page.Plugins.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operations 的本地化字符串。
        /// </summary>
        internal static string Page_Plugins_Operations {
            get {
                return ResourceManager.GetString("Page.Plugins.Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        internal static string Page_Plugins_Restart {
            get {
                return ResourceManager.GetString("Page.Plugins.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Page_Plugins_Settings {
            get {
                return ResourceManager.GetString("Page.Plugins.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string Page_Plugins_Version {
            get {
                return ResourceManager.GetString("Page.Plugins.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New... 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Add {
            get {
                return ResourceManager.GetString("Page.Rules.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Clone {
            get {
                return ResourceManager.GetString("Page.Rules.Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Created {
            get {
                return ResourceManager.GetString("Page.Rules.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove(Del) 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Delete {
            get {
                return ResourceManager.GetString("Page.Rules.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit(E)... 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Edit {
            get {
                return ResourceManager.GetString("Page.Rules.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Rule Definition 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_EditRule {
            get {
                return ResourceManager.GetString("Page.Rules.EditRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Rule Definition 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_NewRule {
            get {
                return ResourceManager.GetString("Page.Rules.NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basics 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Basic {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_CloseDefBox {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.CloseDefBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command Line 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_CommandLine {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.CommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Created {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Enabled {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow Window 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_FollowWindow {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.FollowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide From View 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_HideFromView {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.HideFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move To Desktop 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_MoveToDesktop {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.MoveToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move To Screen 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_MoveToScreen {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.MoveToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ends with 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Op_esw {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Op.esw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 regex 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Op_rim {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Op.rim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contains 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Op_sc {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Op.sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 starts with 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Op_ssw {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Op.ssw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Window 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_PinApp {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.PinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Application of Window 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_PinWindow {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_ProcessName {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Path 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_ProcessPath {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.ProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and Close 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Save {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Title 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Title {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_Updated {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Actions 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_WindowActions {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.WindowActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common Window Rules 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_WindowRules {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.WindowRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window In Screen 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_WinInScreen {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.WinInScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Class 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Rule_WndClass {
            get {
                return ResourceManager.GetString("Page.Rules.Rule.WndClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag(Group) 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Tag {
            get {
                return ResourceManager.GetString("Page.Rules.Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated 的本地化字符串。
        /// </summary>
        internal static string Page_Rules_Updated {
            get {
                return ResourceManager.GetString("Page.Rules.Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Language {
            get {
                return ResourceManager.GetString("Page.Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Menus_Delete {
            get {
                return ResourceManager.GetString("Page.Settings.Menus.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Menus_Duplicate {
            get {
                return ResourceManager.GetString("Page.Settings.Menus.Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Menus_Rename {
            get {
                return ResourceManager.GetString("Page.Settings.Menus.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profiles 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_ProfileManager {
            get {
                return ResourceManager.GetString("Page.Settings.ProfileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Storage {
            get {
                return ResourceManager.GetString("Page.Settings.Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change... 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Storage_ChangeConfigPath {
            get {
                return ResourceManager.GetString("Page.Settings.Storage.ChangeConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent Folder of Configs 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Storage_ConfigRootPath {
            get {
                return ResourceManager.GetString("Page.Settings.Storage.ConfigRootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Theme {
            get {
                return ResourceManager.GetString("Page.Settings.Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Page.Settings.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Page.Settings.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Settings 的本地化字符串。
        /// </summary>
        internal static string Page_Settings_Theme_Sys {
            get {
                return ResourceManager.GetString("Page.Settings.Theme.Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TopLeft to BottomRight, Horizontal 的本地化字符串。
        /// </summary>
        internal static string Page_UI_Label_m0 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TopRight to BottomLeft, Horizontal 的本地化字符串。
        /// </summary>
        internal static string Page_UI_Label_m1 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BottomLeft to TopRight, Horizontal 的本地化字符串。
        /// </summary>
        internal static string Page_UI_Label_m2 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BottomRight to TopLeft, Horizontal 的本地化字符串。
        /// </summary>
        internal static string Page_UI_Label_m3 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TopLeft to BottomRight, Vertical 的本地化字符串。
        /// </summary>
        internal static string Page_UI_Label_m4 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TopRight to BottomLeft, Vertical 的本地化字符串。
        /// </summary>
        internal static string Page_UI_Label_m5 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BottomLeft to TopRight, Vertical 的本地化字符串。
        /// </summary>
        internal static string Page_UI_Label_m6 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BottomRight to TopLeft, Vertical 的本地化字符串。
        /// </summary>
        internal static string Page_UI_Label_m7 {
            get {
                return ResourceManager.GetString("Page.UI.Label.m7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Virtual Desktop Index 的本地化字符串。
        /// </summary>
        internal static string Page_UI_ShowVdIndex {
            get {
                return ResourceManager.GetString("Page.UI.ShowVdIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1-based 的本地化字符串。
        /// </summary>
        internal static string Page_UI_ShowVdIndex_OneBased {
            get {
                return ResourceManager.GetString("Page.UI.ShowVdIndex.OneBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0-based 的本地化字符串。
        /// </summary>
        internal static string Page_UI_ShowVdIndex_ZeroBased {
            get {
                return ResourceManager.GetString("Page.UI.ShowVdIndex.ZeroBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Virtual Desktop Name 的本地化字符串。
        /// </summary>
        internal static string Page_UI_ShowVdName {
            get {
                return ResourceManager.GetString("Page.UI.ShowVdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Desktop Arrangement 的本地化字符串。
        /// </summary>
        internal static string Page_UI_VdArrangement {
            get {
                return ResourceManager.GetString("Page.UI.VdArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Desktop View 的本地化字符串。
        /// </summary>
        internal static string Page_UI_VdView {
            get {
                return ResourceManager.GetString("Page.UI.VdView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field is required. 的本地化字符串。
        /// </summary>
        internal static string Validation_Error_Required {
            get {
                return ResourceManager.GetString("Validation.Error.Required", resourceCulture);
            }
        }
    }
}
