//------------------------------------------------------------------------------
// <auto-generated>
//     Cube3D / plugin UI strings. Keep in sync with Langs.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualSpace.PluginContracts.Resources
{
    using System.Globalization;
    using System.Resources;

    internal class Langs
    {
        private static ResourceManager resourceMan;
        private static CultureInfo     resourceCulture;

        internal Langs()
        {
        }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if ( ReferenceEquals( resourceMan, null ) )
                    resourceMan = new ResourceManager( "VirtualSpace.PluginContracts.Resources.Langs", typeof( Langs ).Assembly );
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }
    }
}
