//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualSpace.PluginContracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualSpace.PluginContracts.Resources.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Duration (ms).
        /// </summary>
        internal static string Cube3D_Settings_AnimationDuration {
            get {
                return ResourceManager.GetString("Cube3D.Settings.AnimationDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Type.
        /// </summary>
        internal static string Cube3D_Settings_AnimationType {
            get {
                return ResourceManager.GetString("Cube3D.Settings.AnimationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Cube3D_Settings_Apply {
            get {
                return ResourceManager.GetString("Cube3D.Settings.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string Cube3D_Settings_Basic {
            get {
                return ResourceManager.GetString("Cube3D.Settings.Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Cube3D_Settings_Close {
            get {
                return ResourceManager.GetString("Cube3D.Settings.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease Mode.
        /// </summary>
        internal static string Cube3D_Settings_EaseMode {
            get {
                return ResourceManager.GetString("Cube3D.Settings.EaseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ease Type.
        /// </summary>
        internal static string Cube3D_Settings_EaseType {
            get {
                return ResourceManager.GetString("Cube3D.Settings.EaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show NotificationGrid on All Screens.
        /// </summary>
        internal static string Cube3D_Settings_ShowNgOnAllScreens {
            get {
                return ResourceManager.GetString("Cube3D.Settings.ShowNgOnAllScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Type.
        /// </summary>
        internal static string Cube3D_Settings_TransitionType {
            get {
                return ResourceManager.GetString("Cube3D.Settings.TransitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube3D Settings.
        /// </summary>
        internal static string Cube3D_Settings_WindowTitle {
            get {
                return ResourceManager.GetString("Cube3D.Settings.WindowTitle", resourceCulture);
            }
        }
    }
}
