<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Plugin\PluginHost\PluginHost.csproj" />
        <ProjectReference Include="..\Commons\Ipc.csproj" />
    </ItemGroup>

</Project>
